## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config3 import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy2_database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cape Town,ZA,-33.9258,18.4232,69.01,82,20,11.50,few clouds
1,1,Hasaki,JP,35.7333,140.8333,50.00,43,20,17.27,few clouds
2,2,Airai,TL,-8.9266,125.4092,62.47,100,100,3.29,overcast clouds
3,3,Lebu,CL,-37.6167,-73.6500,57.83,90,2,13.04,clear sky
4,4,Lincoln,US,40.8000,-96.6670,45.00,80,1,7.43,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df = preferred_cities_df.dropna()
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
11,11,Bengkulu,ID,-3.8004,102.2655,82.53,70,85,4.54,overcast clouds
13,13,Avarua,CK,-21.2078,-159.7750,84.20,70,20,9.22,light rain
14,14,Butaritari,KI,3.0707,172.7902,81.52,83,67,15.19,light rain
24,24,Georgetown,MY,5.4112,100.3354,82.40,57,20,6.91,few clouds
30,30,Sibolga,ID,1.7427,98.7792,81.91,71,14,1.74,few clouds
31,31,Hilo,US,19.7297,-155.0900,78.80,57,75,10.36,broken clouds
39,39,Hobyo,SO,5.3505,48.5268,75.58,81,48,16.69,scattered clouds
40,40,Saint-Pierre,RE,-21.3393,55.4781,75.99,73,0,4.61,clear sky
43,43,Port Keats,AU,-14.2500,129.5500,89.06,66,100,8.63,overcast clouds
44,44,Trinidad,BO,-14.8333,-64.9000,75.43,92,60,2.08,broken clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

Unnamed: 0             156
City                   156
Country                156
Lat                    156
Lng                    156
Max Temp               156
Humidity               156
Cloudiness             156
Wind Speed             156
Current Description    156
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
11,11,Bengkulu,ID,-3.8004,102.2655,82.53,70,85,4.54,overcast clouds
13,13,Avarua,CK,-21.2078,-159.7750,84.20,70,20,9.22,light rain
14,14,Butaritari,KI,3.0707,172.7902,81.52,83,67,15.19,light rain
24,24,Georgetown,MY,5.4112,100.3354,82.40,57,20,6.91,few clouds
30,30,Sibolga,ID,1.7427,98.7792,81.91,71,14,1.74,few clouds
...,...,...,...,...,...,...,...,...,...,...
658,658,Ranong,TH,9.9658,98.6348,82.40,69,40,2.30,scattered clouds
660,660,Vila Velha,BR,-20.3297,-40.2925,78.80,83,40,5.75,scattered clouds
663,663,Bonthe,SL,7.5264,-12.5050,77.58,85,0,6.11,clear sky
664,664,Alofi,NU,-19.0595,-169.9187,80.60,19,90,6.91,light rain
666,666,Manavalakurichi,IN,8.1333,77.3000,80.60,65,20,2.30,haze

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = city_data_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cape Town,ZA,69.01,few clouds,-33.9258,18.4232,
1,Hasaki,JP,50.00,few clouds,35.7333,140.8333,
2,Airai,TL,62.47,overcast clouds,-8.9266,125.4092,
3,Lebu,CL,57.83,clear sky,-37.6167,-73.6500,
4,Lincoln,US,45.00,clear sky,40.8000,-96.6670,
5,New Norfolk,AU,73.00,few clouds,-42.7826,147.0587,
6,Port Elizabeth,ZA,68.00,clear sky,-33.9180,25.5701,
7,Ushuaia,AR,51.80,broken clouds,-54.8000,-68.3000,
8,College,US,-5.80,light snow,64.8569,-147.8028,
9,Bethel,US,30.20,overcast clouds,41.3712,-73.4140,

In [21]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    # 6c. Get latitude and longitude from DataFrame
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print(hotels["results"][0]["name"])
    except (IndexError):
        hotel_df.loc[index, "Hotel Name"] = None
        print("Hotel not found... skipping.")

Radisson Blu Hotel Waterfront, Cape Town
Inubosaki Kanko Hotel
Juvinal Martin
Hostal Las Lilas
Courtyard by Marriott Lincoln Downtown/Haymarket
The Shingles Riverside Cottages
39 On Nile Guest House
Albatros Hotel
Pike's Waterfront Lodge
Courtyard by Marriott Danbury
Bluff Homestead - Guesthouse & Campervan Park
Grage Hotel Bengkulu
Hotel not found... skipping.
Paradise Inn
Isles Sunset Lodge
Hotel not found... skipping.
Westmark Sitka
Hotel not found... skipping.
Kilabuk Lodge
Hotel Ker Izel
Gina's Guesthouse - Upernavik
大雪荘
Гостиница "Анадырь"
Airbnb rooms
Cititel Penang
Hotel Dreams Del Estrecho
Hospitality Esperance
Talnakh Hotel
St Ives Hobart Accommodation Tasmania
Gallows Cove
Hotel Syariah CN Darussalam
Hilo Hawaiian Hotel
Observatory Guest House
Dredge 7 Inn
Ted McQuinn Trust
Gostinitsa
Hotel Arctic
Hotel not found... skipping.
Best Western Hotel Samantta
Halane Hotel and Restaurent
Lindsey Hôtel
Hotel Mayros
The Explorer Hotel
TDC Village (Hundred Man Camp)
Hotel Piesta
Hotel not found... skipping.
Manoir Du Bonheur
La Tahzan Guest House
Pousada Porto Praia
Tu Casa
Gostinitsa "Zapolyar'ye"
Six Acres Bed & Breakfast
Shellharbour Resort & Conference Centre
Hotel not found... skipping.
Camping municipal d'Albanel
Hampton Inn & Suites Jamestown
Hotel Chique Chique
Villa Enata
अन्नी घर, जुम्ला - Anni Ghar
Hotel not found... skipping.
HAMDAN PLAZA HOTEL SALALAH
Al Safir Hotel & Tower
Frobisher Inn
Hotel Kap Farvel
Qamaq Hotel
Hampton Inn & Suites Lebanon
NYSC Permanent Orientation Camp, Iseyin, Oyo State
Tourist House - Sablino
فندق الفردوس
Carrís Almirante
Red Lion Hotel Coos Bay
The Halyards Hotel
Ellie's Villa
Qaanaaq Hotel
Hotel not found... skipping.
Lamana Hotel
Kost H.Syamsuddin
Bredasdorp Country Manor
CeBlue Villas & Beach Resort
Severnoye Zoloto
Keleti Beach Resort
Pestana Bahia Praia
Hotel not found... skipping.
Sheraton Kauai Resort at Coconut Beach
Shanti Maurice Resort & Spa
King Eider Inn
Hotel not found... skipping.
Hotei
Almadina Hotel
NUR
Heritage Bagh by Himalayan Musk
Hotel Vittoria
Pension Maro'i
The Ritz-Carlton, Half Moon Bay
Best Western Kodiak Inn And Convention Center
Hotel Uauá
Hotel Chik Chik Namibe
Recanto dos Ferreiras
Casa Maquia
Homewood Suites by Hilton Edgewater-NYC Area
Vahmoneh Lodge Vanimo
Hotel Santa Mônica
Conrad Bora Bora Nui
Shandrani Beachcomber Resort & Spa
Hotel not found... skipping.
Hotel not found... skipping.
Burntwood Hotel
Bora-Bora Pearl Beach Resort & Spa
Hospitality Carnarvon
Hotel Pigalle
Wardenclyffe Volgo&Balt
Hosteria Sampedro
Super 8 by Wyndham Fortuna
Morwell Motel
SEGAYA PROPERTY
Hotel not found... skipping.
مقبرة ال مجمل
Chambres d'hôte "La Trinité"
Holiday Inn Express Antofagasta
Kak Doma
Castillo Galapagos
Hotel not found... skipping.
Hotel do Campo
Holiday Inn Express & Suites Vermillion
Samyang Beach Villa
Foyer ADM
Scenic Hotel Southern Cross
Busta House Hotel
OYO 884 Rumoh PMI Hotel
Hotel Los Arcos
Hotel not found... skipping.
Laxmi Palace
Nordre Silda.
Apel'sin
Oyster Bay House Rental
Hotel not found... skipping.
Desert Palms Alice Springs
End of The Road Ltd.
Valle Aridane
Best Western Plus Abbey Inn
Ruidu Hotel
Quinta Splendida Wellness & Botanical Garden
Mutoko Hotel
Bam Tourist Hotel
Kaitangata Motor Camp
Case de Passage De la Prefecture
ARTIEM Capri
Hampton Inn & Suites Morgan City
Rahat Hotel
Quinta da Meia Eira
Nuli Sapi
Asad U Bajeer Hotel
Benin Metropole Hotel
Hotel not found... skipping.
Molika Springs Motel
Laoyutang Resort
Puri Brata
Hotel Londres
Derogongan Residence
CHACARA BAILLY
Gostinitsa Ust'-Uda Shans
IBCO REAL ESTATE PROPERTY
Hotel Elimar
Apartment Av. Castelao
Hotel not found... skipping.
Vardø Hotel AS
HS Hotsson Smart Acapulco
Leuaina Beach Resort and Spa
Grand Kecubung Hotel
Samparada & Gestiada Residences
Hotel not found... skipping.
Hotel Castelo
Hotel not found... skipping.
Lymina
Hotel not found... skipping.
Hotel San Alberto Plaza
Gostinitsa Severyanka
Beau Site
Emeraude Beach Attitude Hotel
Ramada Hotel & Suites by Wyndham Ballina Byron
Hotel not found... skipping.
Eureka Inn Trademark By Wyndham
Zaky Homestay
Pousada Galvão
Storyboard Beach Resort
Casa Das Faias
Hotel Tesoro Los Cabos
奄美ポートタワーホテル
The Red House
Maitai Lapita Village Huahine
Rydges Port Macquarie
KOLPING Hotel
Hotel not found... skipping.
Hospedaje Costa Bella
Northland Motor Hotel
Arktika
Shinomontazh
塔河宾馆
Pemberton Valley Lodge
Apartament
Oota Ryokan
Old Mill Hotel
Westmark Fairbanks Hotel & Conference Center
Auberge des Cocotiers Boali poste
Ilikchin
Hotel Cristal
Hotel not found... skipping.
Xinxing Lidu Hotel
Баня Сауна Млинів. Сауна Млинов. Баня Сауна Дубно.
Candlewood Suites Craig-Northwest
Veranda Paul et Virginie Hotel & Spa
Port Lincoln Hotel
Casa Tia Villa
Ungoofaaru Inn
Taavi Vartia Tuotannot
Mess keban agung
Austral Hotel
Fletcher Hotel-Restaurant De Wageningsche Berg
Volcano Sea View Tree House
Gostinichnyy Kompleks Aylgy
Hotel Juba
Montana Hotel Syariah
PT PPI Lamongan Tambak C
Civil Registry - Sohag 1
โรงแรมแสงชัย
Hotel Pousada Tropical
Scandic Plaza Borås
Hotel On The Rock by Prasanthi
Desert Gardens Hotel - Ayers Rock Resort
Mini Hotel Central
Shingu UI Hotel
Hotel Svetlogorsk JBIK
Cricaré Praia Hotel
Misty Waves Boutique Hotel
Vakantiepark Kijkduin
Dali Travelling With Hostel
Tobin Lake Motel
La Riviera Hotel Colonial
Namatanai Hotel
Casa Laguna, Bed & Breakfast
Shivalik Camps & Resort
Holiday Inn Express & Suites North Platte
Hotel La Villa Couacou
Sjybrygga fiskecamp
Yicheng Hotel
Delong Hotel
Hotel not found... skipping.
Masuda Green Hotel Morris
Il Conte Dell'Etna
Hotel Mout View
H10 Estepona Palace
Bungalow 63
Okhotnich'ye Khozyaystvo "Bober"
Maui Seaside Hotel
Amosphère, complexe hôtelier
ROREM'S BOARDING HOUSE
Kandrian Station
Sandpiper Motel
Hotel Central
Broadwater Mariner Resort
Motel 6 Sinton, TX
Atlantis Hotel
Postoyalyy Dvor
Oustaz Vame DIAKITE
The Fort Nelson Hotel
Hotel Touring Club
Radisson Blu Polar Hotel, Spitsbergen
Hotel not found... skipping.
Mercure Hotel Frankfurt Eschborn Helfmann Park
Lakselv Hotel
Motel' Osakarovka
Hotel not found... skipping.
VS Villa
Hotel Mounia Fès
Lakatoro Palm Lodge
La Quinta Inn by Wyndham Abilene
Big Red's
Gillespie House Inn
Hotel not found... skipping.
Residencial Eluzai
Chez Honorable Chapiou
Residencial Karime
Comfort Hotel Great Yarmouth
North Gate Hostel
Fengyuan Hotel
Companionship Hotel
Nova Inn Inuvik
Shell Zhangjiakou City Qiaodong District Ginza Hotel
Hotel Panorama
ibis budget Newport
Sebinkarahisar Ogretmenevi
Stonewall Inn
Hotel Arena Gruesa
Casa Hotel Real
InterContinental Riyadh
Ta'Bertu Guest House
Holiday Inn Express Lompoc
Hotel Fontana Plaza
Mehamn Arctic Hotel AS
Medhufushi Island Resort
Pousada Rio Current
Skjervøy Byggeservice AS
Hotel Patagonia
Hotel Kyocera
Airport Inn
Fortuna
Inishowen Gateway Hotel
Swiss-Belhotel Borneo Banjarmasin
Hotel hewa bora
Royal Exchange Hotel
Cole Porter Inn
Rivendell Respite
Resorts Resource Group International
The recreation center "Green Lake"
SomeWhere Else boutique resort
Hôtel & Restaurant DIANA Ambilobe
Yalemd
Blackwater Motor Inn
Bashneft
София
Motel 6 Estevan, SK
Hotel Monarque Tottori
Hotel not found... skipping.
Holiday Inn Express & Suites Elk Grove Central - Hwy 99
Skogly overnatting (Stengt/closed)
Nuevo Hotel Plaza
Hotel San Juan
Wingate By Wyndham Rome
Hotel not found... skipping.
El Medina
Hotel not found... skipping.
Gran Hotel Mar del Plata
Container Inn Puerto Vallarta
ibis Styles Mt Isa Verona
Scoop Guest House
Amaloh Boutique Resort
Kwakuwahi Lodge
Hotel not found... skipping.
محل الشريف محمد العايب
Hotel not found... skipping.
Sole E Monte
Oregon Place Guest House
College of Nursing & Midwifery Female's Hostel
Hotel Port Dénia
Lords Inn Porbandar
Hampton Inn & Suites Vacaville-Napa Valley
Diego De Almagro Coyhaique
Sherwood Motel
Apartments in Inta city
Auberge Tembina Betaré Oya
Forest Rest House
Hotel not found... skipping.
La Nueva España
Hotel not found... skipping.
Ayre Hotel
Cossam Guest House
Bryn Woodlands House
Ooo "Kvarkeno"
JKL Inc. R.V Park and Storage
Mini Hotel Veshnyaki
Northern Light Inn & Max's Restaurant
Hotel not found... skipping.
Hampton Inn Ukiah
Villa Park Hotel | Natal
Hôtel Trois Étoiles de Biltine
Shimoda Tokyu Hotel

Bjarnabúð
Anadolu Palace Hotel
InTown Suites Extended Stay Denver CO - Englewood
Sea Lounge! Bar, Club & Restaurant
ALETHEIA Appartement Sinnamary
Sangam hotel and lodge
زكريا عبد الفتاح سليم
Elburg Hotel & Stadscafé the Tapperij
Hotel California Petatlán
Bobo
Hotel JM Puerto del Rosario
Hotel Kou-Bugny
Noona Noona Hotel
Amberton Cathedral Square Hotel Vilnius
Hotel RIKMAN Continental
Red Sea Hotel
Hotel Miramar
Posada del Inti Centro
Flem Cabins
Ramina
Gostinitsa Tommot
Sur Plaza Hotel
Praia Hotel Imbituba
Codrington Gardens Bed And Breakfast
Guest House Motel
Sevgi Otel
SHAFI SLAB POLISHING INDUSTRIES
Mantra Nelson Bay
Guest L'Amour
Hotel not found... skipping.
Hotel not found... skipping.
Carolyn Beach Inn & Restaurant
Aklavik Inn
Jamal sons showroom
Hotel Atoll Emerald Miyakojima
Qasr Hotel
Guest House Ruslan Nurata & Tours
Hotel not found... skipping.
Quinta Samay
Hotel not found... skipping.
Fengshui Residence
Hotel del Comahue
Hotel Dawei
Yubileinaya Hotel
Hotel not found... skipping.
Hostel At-Bashy
Toyoko Inn Iwaki Ekimae
Hotel NH Collection Palacio de Avilés
Hotel not found... skipping.
Guayacan Real
Stamford Plaza Sydney Airport Hotel & Conference Centre
Abbott's Bed & Breakfast
Hotel Brisas de San Miguel
Hotel "Sob"
West Plains Motel
Crowne Plaza Ordos
Rainforest Haven Inn
კურორტი ზეკარი/Resort Zekari
HOTEL ISABELA
Guest House HESADA
Piligrim
Hyatt Regency Jacksonville Riverfront
St. Christopher's Hotel
Haajy Guest House 1
Dan Caesarea
Hotel not found... skipping.
Hotel Porto do Sol
Harmony Inn
Blue Bay Lodge
Hotell Frøya
Huarpes Hotel
Chongli Xuexiang Family Express Inn
Hotel San Isidro Oficial
Boyue boutique Hotel
Yeet Hotel
Xcoco Inn
Klover Hotel
Amangalla
Holiday Inn Express Roseville-St. Paul
Casillas De Morales 59.
Parkside Inn
Residencial Luismar
Hotel not found... skipping.
Hotel not found... skipping.
Hotel Valentine, Haute-Garonne
Prestige Hotel
Mantra Trilogy Cairns
Executive Inn Owatonna
Undulata Country Lodge
Grand Dafam Bela Ternate
Pension Feldgärtenhof
OYO 90038 Dalyla Inn Chalet
مضيفة المركز
Le Refuge
Hotel Boutique Las Azucenas
Hotel Kumar International
Velichko T.p., Gostinitsa
GRAN HOTEL SANABRIA
Beringgorski
Americas Best Value Inn Ozark Springfield
Toyoko-Inn Izumoshi ekimae
Petit Hotel Hostatgeria Sant Salvador
Vasavi Satram
Hotel Urbano
Hotel not found... skipping.
Netalco Connects
Baza Otdykha
Residence Inn by Marriott Boston Norwood/Canton
Thank Inn Chain Hotel shanxi weinan linwei district jiefang road
Durrant House Hotel
Hotel Luta Resort
Hotel Terramar
Eware Refugio Amazonico
Shoukat Hussain Hotal
Guest House Orkhideya
Fjord-Fishing AS, Property & Housing Co.
Chenango Valley State Park
Hotel Villa Ombrosa
Hotel Edi
Hotel not found... skipping.
"Kunakkhana"
สถานที่จัดงานแต่ง SOFEE & DORN
BON Hotel Waterfront Richards Bay
Monte Carlo
Hotel not found... skipping.
Base Lodging
Hotel Praia Morena
صاحبة الفخامة
Hotel Karysmã
Ptarmigan Inn Hotels
OYO 1577 Hotel Shree Hari Grand
Hotel Viktoria
Beachside Resort Whitianga
Hotel not found... skipping.
Deep River Motel
Hotel not found... skipping.
Protea Hotel by Marriott Knysna Quays
Hotel not found... skipping.
Marriage Registry Office Joypur Road
Pirineos
Snt "Druzhba"
Cartagena Marlin hostel
McCracken Country Club
Hotel not found... skipping.
Hôtel M'Sallah
Sheraton Santiago Hotel and Convention Center
Yuehai Hotel
Hotel La Paz
Aridolf Resort Wellness and Spa
Uyutnaya Mini-Hotel
Hotel not found... skipping.
Lakeview Lodge
Hotel not found... skipping.
Embassy Suites by Hilton Huntsville Hotel & Spa
Egorkino Hotel
Hotel not found... skipping.
Pondok Wisata Elim
Beleza Pura B&B
Hotel Ultramar
Howard Johnson by Wyndham Modesto Ceres
Grand 0773 Hotel
Ruth Guest House
دفتر نمایندگی شرکت بازاریابان ایرانیان زمینBIZ
Hotel Sirenetta
Hotel not found... skipping.
Courtyard by Marriott Houma
Hotel not found... skipping.
Royal Plaza
Shahrekord Tourist Hotel
Hotel not found... skipping.
Katsuura Hotel Mikazuki
Sun Stay Kaseda
Hotel not found... skipping.
Pereybere Hotel & Spa
Guest House Hewa Bora
Hotel not found... skipping.
East Hills Bed & Breakfast Inn
Guest House Aki
Premier Inn Aberdeen City Centre hotel
Swiss-Belhotel Ambon
Park Inn Motel
Batemans Bay Marina Resort
Hotel not found... skipping.
Family
Crest Hotel
INN NEW HORIZON
Hotel not found... skipping.
Montta - active camping / campsite Montan
Hotel not found... skipping.
Pousada dos Navegantes
Hotel Kununurra
حامد محمد نور
Ikathouse
Budget Guesthouse Borgustova

ConnectionError: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/place/nearbysearch/json?radius=5000&type=lodging&key=AIzaSyAVdGnlr6qExSIBpTPjggvfHy0uleC9dG4&location=50.1001%2C-91.917 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f96eac76190>: Failed to establish a new connection: [Errno 50] Network is down'))

In [16]:
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cape Town,ZA,69.01,few clouds,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
1,Hasaki,JP,50.00,few clouds,35.7333,140.8333,Inubosaki Kanko Hotel
2,Airai,TL,62.47,overcast clouds,-8.9266,125.4092,Juvinal Martin
3,Lebu,CL,57.83,clear sky,-37.6167,-73.6500,Hostal Las Lilas
4,Lincoln,US,45.00,clear sky,40.8000,-96.6670,Courtyard by Marriott Lincoln Downtown/Haymarket

In [42]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df = hotel_df.dropna()
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cape Town,ZA,69.01,few clouds,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
1,Hasaki,JP,50.00,few clouds,35.7333,140.8333,Inubosaki Kanko Hotel
2,Airai,TL,62.47,overcast clouds,-8.9266,125.4092,Juvinal Martin
3,Lebu,CL,57.83,clear sky,-37.6167,-73.6500,Hostal Las Lilas
4,Lincoln,US,45.00,clear sky,40.8000,-96.6670,Courtyard by Marriott Lincoln Downtown/Haymarket
...,...,...,...,...,...,...,...
668,Lubango,AO,62.56,overcast clouds,-14.9172,13.4925,Hotel Serra da Chela
669,Turukhansk,RU,-5.91,light snow,65.8167,87.9833,"ООО ""Туруханская пушнина"""
670,Nagato,JP,46.40,broken clouds,34.3833,131.2000,いそう庵
671,Hecun,CN,42.44,overcast clouds,36.5333,114.1111,Yijia Hotel
672,Aksarka,RU,-7.46,overcast clouds,66.5606,67.7975,

In [50]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [52]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>County</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [53]:
# 11a. Add a marker layer for each city to the map. 
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=(max_temp>0),dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))